### ISSUE TITLE
[Feature Request] 希望增加地区筛选

### ISSUE THREAD

**Issue by rakuyoMo** [hehehai/x-hiring#2]
岗位可以搜索，地区的话就有些麻烦了，比如搜 “北京iOS” 搜不到，但是搜 “北京” 可以发现一个移动端职位。

**Comment by hehehai** [comment]
@rakuyoMo 好的，安排（预计下周会支持）

- [x] 实现多词条搜索，行为（前端 北京）将搜索 “前端” 和 “北京”
- [x] 搜索支持标签检索

**Comment by hehehai** [comment]
@rakuyoMo 新版本已发布 #3
