### ISSUE TITLE
推荐抓取阮一峰的《谁在招人》

### ISSUE THREAD

**Issue by GQMai** [hehehai/x-hiring#4]
如题： https://github.com/ruanyf/weekly/issues/4075

**Comment by hehehai** [comment]
@GQMai 安排（预计下周-4 月）

- [x] 每日同步 https://github.com/ruanyf/weekly/issues/4075 Github Issues [谁在招人] 仅获取最新的一个
- [x] 获取所有 post，使用 AI 分析（已分析 post 无需再次分析）

**Comment by hehehai** [comment]
@GQMai 已实现：https://x-hiring.hehehai.cn

<img width="1620" alt="image" src="https://github.com/hehehai/x-hiring/assets/12692552/728689c0-8be4-4326-841d-2105854485b0">
