### ISSUE TITLE
Can't reach database server at `0.0.0.0`:`5432`

### ISSUE THREAD

**Issue by DanielDeng3** [hehehai/x-hiring#5]
如题，git clone并创建.env后，运行报错，数据库没运行吗，macos 13.6 系统
`Can't reach database server at `0.0.0.0`:`5432`

Please make sure your database server is running at `0.0.0.0`:`5432`.
    at async Module.$$ACTION_0 (/Users/jianhao.deng/Daniel_Git/x-hiring/.next/server/chunks/_1de711._.js:1264:22)
    at async HomePage (/Users/jianhao.deng/Daniel_Git/x-hiring/.next/server/chunks/_1de711._.js:1350:24)
digest: "1673585830"
  51 |     }`

**Comment by hehehai** [comment]
@DanielDeng3 请使用你本地的PostgreSQL 数据库地址，目前的地址是 demo

**Comment by DanielDeng3** [comment]
谢谢你的回复，我尝试搭建一下数据库再试试。

**Comment by DanielDeng3** [comment]
`__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$server$2f$db$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["db"].job.findMany( The column `job.originId` does not exist in the current database.`

`x_hiring=# \d job
                 Table "public.job"
  Column  |  Type   | Collation | Nullable | Default
----------+---------+-----------+----------+---------
 originid | text    |           |          |
 id       | integer |           |          |
`
我创建了表，并添加了一些列，为什么还是提示找不到job.originId呢

**Comment by hehehai** [comment]
@DanielDeng3 数据库使用 Prisma ORM，需要做 Schema 到数据的映射，可以使用 package.json 中的 `db:push`

在终端运行：`npm run db:push`

- 开发情况请使用：https://www.prisma.io/docs/orm/prisma-migrate
- 更多 Prisma cli 使用方式：https://www.prisma.io/docs/orm/tools/prisma-cli

**Comment by DanielDeng3** [comment]
docker部署的方式会更好吗

**Comment by DanielDeng3** [comment]
`> prisma db push

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "x_hiring", schema "public" at "0.0.0.0:5432"
Error: ERROR: permission denied for table job
   0: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:433`

**Comment by DanielDeng3** [comment]
我终于运行成功了，我在.env里面，修改了连接数据的用户名，看来是权限问题导致无法把配置推送到数据库里。我是数据库小白。。。
谢谢
