### ISSUE TITLE
希望能增加 RSS 订阅 / 邮件订阅

### ISSUE THREAD

**Issue by onlyacat** [hehehai/x-hiring#6]
目前只能通过网页方式访问，需要记得定期来看，比较麻烦

希望能增加 RSS 或者 News Letter 或者 邮件订阅 的方式，这样能收到推送~

PS: 看到最底下有 RSS 订阅的 TODO 了

**Comment by hehehai** [comment]
@onlyacat 安排，在日程中了

- [x] RSS 订阅

News Letter 需要写成本，RSS 合适些

**Comment by hehehai** [comment]
@onlyacat rss 订阅已发布，支持订阅最新 20 条数据，订阅地址 `http://x-hiring.hehehai.cn/feed.xml`

<img width="1457" alt="image" src="https://github.com/hehehai/x-hiring/assets/12692552/2e002725-d894-47a3-bcc5-06044441b4bd">

**Comment by baerwang** [comment]
hi，这是什么软件呀

**Comment by hehehai** [comment]
> hi，这是什么软件呀

@baerwang 是 [NetNewsWire](https://netnewswire.com/) 支持 Mac、iPhone、iOS

**Comment by baerwang** [comment]
> > hi，这是什么软件呀
> 
> @baerwang 是 [NetNewsWire](https://netnewswire.com/) 支持 Mac、iPhone、iOS
谢谢
