### ISSUE TITLE
RSS 没有实时更新

### ISSUE THREAD

**Issue by onlyacat** [hehehai/x-hiring#8]
点开首页最新的是4月7号的，不过RSS 里头的还是 3月31号的

看看能不能麻烦修一下😂

<img width="1042" alt="image" src="https://github.com/hehehai/x-hiring/assets/29370032/0878de02-e0a7-41f1-92f8-7445c34652f0">
<img width="937" alt="image" src="https://github.com/hehehai/x-hiring/assets/29370032/d014e891-af26-48b8-84c3-42bc0517f2dd">

**Comment by hehehai** [comment]
@onlyacat 好了，修复了，缓存问题.
